"""Add model market tables

Revision ID: fe28b8e0d255
Revises: 001
Create Date: 2026-01-15 02:47:07.008867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe28b8e0d255'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_recommendation_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('endpoint_url', sa.String(length=500), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('api_key_required', sa.Boolean(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('additional_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_rec_config_active', 'ai_recommendation_config', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_recommendation_config_id'), 'ai_recommendation_config', ['id'], unique=False)
    op.create_table('hf_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('sha', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('pipeline_tag', sa.String(length=100), nullable=True),
    sa.Column('library_name', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('card_data', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('transformers_info', sa.JSON(), nullable=True),
    sa.Column('indexed_tags', sa.JSON(), nullable=True),
    sa.Column('indexed_categories', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('details_fetched', sa.Boolean(), nullable=True),
    sa.Column('detail_synced_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hf_models_author', 'hf_models', ['author'], unique=False)
    op.create_index('ix_hf_models_downloads', 'hf_models', ['downloads'], unique=False)
    op.create_index(op.f('ix_hf_models_id'), 'hf_models', ['id'], unique=False)
    op.create_index('ix_hf_models_last_modified', 'hf_models', ['last_modified'], unique=False)
    op.create_index('ix_hf_models_likes', 'hf_models', ['likes'], unique=False)
    op.create_index('ix_hf_models_model_id', 'hf_models', ['model_id'], unique=False)
    op.create_index('ix_hf_models_pipeline_tag', 'hf_models', ['pipeline_tag'], unique=False)
    op.create_table('model_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_models', sa.Integer(), nullable=True),
    sa.Column('synced_models', sa.Integer(), nullable=True),
    sa.Column('updated_models', sa.Integer(), nullable=True),
    sa.Column('failed_models', sa.Integer(), nullable=True),
    sa.Column('skipped_models', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('watermark_last_modified', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('current_page', sa.Integer(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('cancellation_requested', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_sync_logs_id'), 'model_sync_logs', ['id'], unique=False)
    op.create_table('user_model_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_bookmarks_model_id', 'user_model_bookmarks', ['model_id'], unique=False)
    op.create_index('ix_user_bookmarks_user_id', 'user_model_bookmarks', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_model_bookmarks_id'), 'user_model_bookmarks', ['id'], unique=False)
    op.drop_constraint(op.f('user_password_resets_token_key'), 'user_password_resets', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_password_resets_token_key'), 'user_password_resets', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_model_bookmarks_id'), table_name='user_model_bookmarks')
    op.drop_index('ix_user_bookmarks_user_id', table_name='user_model_bookmarks')
    op.drop_index('ix_user_bookmarks_model_id', table_name='user_model_bookmarks')
    op.drop_table('user_model_bookmarks')
    op.drop_index(op.f('ix_model_sync_logs_id'), table_name='model_sync_logs')
    op.drop_table('model_sync_logs')
    op.drop_index('ix_hf_models_pipeline_tag', table_name='hf_models')
    op.drop_index('ix_hf_models_model_id', table_name='hf_models')
    op.drop_index('ix_hf_models_likes', table_name='hf_models')
    op.drop_index('ix_hf_models_last_modified', table_name='hf_models')
    op.drop_index(op.f('ix_hf_models_id'), table_name='hf_models')
    op.drop_index('ix_hf_models_downloads', table_name='hf_models')
    op.drop_index('ix_hf_models_author', table_name='hf_models')
    op.drop_table('hf_models')
    op.drop_index(op.f('ix_ai_recommendation_config_id'), table_name='ai_recommendation_config')
    op.drop_index('ix_ai_rec_config_active', table_name='ai_recommendation_config')
    op.drop_table('ai_recommendation_config')
    # ### end Alembic commands ###
